### PR TITLE
Updated to work in Sketch 43.2

### PR DESCRIPTION
**Pull request by JesseBilsten**
Removed the old header references, replaced with layer.duplicate(), deselection and re-selection of copied layers.

I'm not sure if you'll want to keep the backwards compatible header references or not.

### CODE REVIEW

**Comment by pixelyze** [comment]
Thx guy !

**Comment by turbobabr** [comment]
Thanks for the update @JesseBilsten ! 🍻

**Comment by robinrowell** [comment]
Thanks for saving my sanity @JesseBilsten ! A must-have plugin has been fixed.

**Comment by miguelsolorio-zz** [comment]
So happy to have found this fix, thank you @JesseBilsten!

**Pull request merged**
